### ISSUE TITLE
How to Run Vue-stisla

### ISSUE THREAD

**Issue by reyzaraf** [lkloon123/vue-stisla#1]
Hello sir, can i ask to you how to use this vue-stisla after clone from git ? 
does it run as usual vue?

**Comment by reyzaraf** [comment]
after i clone this repo in my local and running command npm install + npm run serve its not work.

**Comment by lkloon123** [comment]
@reyzaraf hi, sry this is currently halt, have a look at this https://github.com/stisla/stisla/issues/32#issuecomment-503372677

**Comment by reyzaraf** [comment]
Ohh okay i see.. thanks for the information sir.
